#!/bin/bash

if [[ -z $DAY ]]; then
	echo >&2 "Usage: DAY=8 $0 [... file names]"
	exit 1
fi

i=720
for f in "$@"; do
	hour=$((i/60))
	min=$((i%60))
	stamp=$(printf "198001%02d%02d%02d" $DAY $hour $min)
	echo $stamp $f
	touch -mt $stamp $f
	i=$((i+1))
done
